name: "cqrs"
version: 3.0.2
description: CQRS client with helper Command/Query classes for Dart
homepage: https://leancode.pl/
environment:
  sdk: ">=2.0.0<3.0.0"
dependencies:
  http: ^0.12.0
